# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b4fbac95cd46a0d63b0f49d98215af7f8fe671280ede73cfe1c15a9040d129d81f1711550e88a69c951582289d7a03129b230c32666bdf4b4817ced4200b562

test:
  secret_key_base: f6730aeb5ee30131e9a00f0e70d3d1c5073ba7717337cb63e14f78b7be989b95f68a6cc87f8d69cbac2c1441a06353158e32a01db1c32c5f24c87d99fed21f62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
